services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecomapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-cold-shape-a2993dbf-pooler.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_WEC4pjxIO6Tn
      SPRING_JPA_SHOW_SQL: "true"
      JWT_SECRET: JgK1xNmNq2pPzqKnESw91A+pkBb1knk4FzXbUeLzmUM=
      JWT_EXPIRATION: "315360000000"
