# =========================
# App
# =========================
spring.application.name=EcomApp

# =========================
# DataSource (defaults = H2 local)
# Override these on Railway for Postgres
# =========================
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.url=${DB_URL:jdbc:h2:file:./.localdb/ecomdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# =========================
# JPA / Hibernate
# =========================
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=validate

# =========================
# Flyway (uses same datasource unless overridden)
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=${SPRING_FLYWAY_URL:${spring.datasource.url}}
spring.flyway.user=${SPRING_FLYWAY_USER:${spring.datasource.username}}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD:${spring.datasource.password}}

# =========================
# H2 console (handy locally)
# =========================
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console

# =======================
