spring.application.name=EcomApp
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.datasource.url=jdbc:postgresql://localhost:5432/DBNAME
spring.datasource.username=postgres
spring.datasource.password=your_password
