CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    slug        VARCHAR(255),
    price       DOUBLE PRECISION,
    description VARCHAR(255),
    quantity    INTEGER,
    rating      DOUBLE PRECISION,
    images      TEXT[],
    category_id BIGINT,
    status      VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);