CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    otp           VARCHAR(255)                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);
INSERT INTO users (email, password_hash, role, status, created_at, otp)
VALUES (
           'admin@example.com',
           '$2a$10$69u3D/FXOY0loIcG4UI6LO9n5bk9LcxKBRA.WNlfPxG9QIS0tU1XW', -- bcrypt of: admin123
           'ADMIN',
           'AVAILABLE',
           NOW(),

        null
       );