CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)      NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    password_reset_token VARCHAR(255),
    password_reset_expires TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_27629ccf2080eea417f75bd2b UNIQUE (email);

INSERT INTO users (email, password_hash, role, status, created_at)
VALUES (
           'admin@example.com',
           '$2a$10$69u3D/FXOY0loIcG4UI6LO9n5bk9LcxKBRA.WNlfPxG9QIS0tU1XW', -- bcrypt of: admin123
           'ADMIN',
           'AVAILABLE',
           NOW()
       );