CREATE TABLE cart
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE cart_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    price      DECIMAL                                 NOT NULL,
    cart_id    BIGINT,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);
INSERT INTO cart (id, user_id)
VALUES
    (1, 1),
    (2, 2),
    (3, 3);