-- ================================
-- CATEGORIES
-- ================================
CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        TEXT                                    NOT NULL,
    slug        TEXT,
    image       TEXT,
    description TEXT,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

-- Idempotent category seeds (no MERGE; H2-safe)
INSERT INTO categories (name, slug, image, description)
SELECT 'Electronics', 'electronics', 'https://i.imgur.com/ZANVnHE.jpeg', 'All Type of zeros and ones products'
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Electronics');

INSERT INTO categories (name, slug, image, description)
SELECT 'REST-Update', 'rest-update', 'https://placeimg.com/640/480/any', 'Rest Update Type Products'
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'REST-Update');



-- ================================
-- PRODUCTS
-- ================================
CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       TEXT,
    slug        TEXT,
    price       DOUBLE PRECISION,
    description TEXT,
    quantity    INTEGER,
    rating      DOUBLE PRECISION,
    category_id BIGINT,
    status      TEXT,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

-- Seed products (examples)
INSERT INTO products (title, slug, price, description, quantity, rating, category_id, status)
SELECT
    'Sleek White & Orange Wireless Gaming Controller',
    'sleek-white-orange-wireless-gaming-controller',
    69,
    'Elevate your gaming experience with this state-of-the-art wireless controller, featuring a crisp white base with vibrant orange accents. Designed for precision play, the ergonomic shape and responsive buttons provide maximum comfort and control for endless hours of gameplay. Compatible with multiple gaming platforms, this controller is a must-have for any serious gamer looking to enhance their setup.',
    NULL, NULL,
    (SELECT id FROM categories WHERE name = 'Electronics'),
    'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'sleek-white-orange-wireless-gaming-controller');

INSERT INTO products (title, slug, price, description, quantity, rating, category_id, status)
SELECT
    'Sleek Comfort-Fit Over-Ear Headphones',
    'sleek-comfort-fit-over-ear-headphones',
    28,
    'Experience superior sound quality with our Sleek Comfort-Fit Over-Ear Headphones, designed for prolonged use with cushioned ear cups and an adjustable, padded headband. Ideal for immersive listening, whether you''re at home, in the office, or on the move. Their durable construction and timeless design provide both aesthetically pleasing looks and long-lasting performance.',
    NULL, NULL,
    (SELECT id FROM categories WHERE name = 'Electronics'),
    'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'sleek-comfort-fit-over-ear-headphones');

INSERT INTO products (title, slug, price, description, quantity, rating, category_id, status)
SELECT
    'Sleek Modern Leather Sofa',
    'sleek-modern-leather-sofa',
    53,
    'Enhance the elegance of your living space with our Sleek Modern Leather Sofa. Designed with a minimalist aesthetic, it features clean lines and a luxurious leather finish. The robust metal legs provide stability and support, while the plush cushions ensure comfort. Perfect for contemporary homes or office waiting areas, this sofa is a statement piece that combines style with practicality.',
    NULL, NULL,
    (SELECT id FROM categories WHERE name = 'REST-Update'),
    'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'sleek-modern-leather-sofa');

-- (⚠️ Add the rest of your products here using the same INSERT … SELECT … WHERE NOT EXISTS pattern)



-- ================================
-- PRODUCT IMAGES
-- ================================
CREATE TABLE product_images
(
    product_id BIGINT NOT NULL,
    image      TEXT
);

ALTER TABLE product_images
    ADD CONSTRAINT fk_product_images_on_product FOREIGN KEY (product_id) REFERENCES products (id);

INSERT INTO product_images (product_id, image)
SELECT (SELECT id FROM products WHERE slug = 'sleek-white-orange-wireless-gaming-controller'), 'https://i.imgur.com/ZANVnHE.jpeg';

INSERT INTO product_images (product_id, image)
SELECT (SELECT id FROM products WHERE slug = 'sleek-white-orange-wireless-gaming-controller'), 'https://i.imgur.com/Ro5z6Tn.jpeg';

INSERT INTO product_images (product_id, image)
SELECT (SELECT id FROM products WHERE slug = 'sleek-comfort-fit-over-ear-headphones'), 'https://i.imgur.com/SolkFEB.jpeg';

INSERT INTO product_images (product_id, image)
SELECT (SELECT id FROM products WHERE slug = 'sleek-comfort-fit-over-ear-headphones'), 'https://i.imgur.com/KIGW49u.jpeg';

INSERT INTO product_images (product_id, image)
SELECT (SELECT id FROM products WHERE slug = 'sleek-modern-leather-sofa'), 'https://i.imgur.com/Qphac99.jpeg';

INSERT INTO product_images (product_id, image)
SELECT (SELECT id FROM products WHERE slug = 'sleek-modern-leather-sofa'), 'https://i.imgur.com/dJjpEgG.jpeg';
