CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        TEXT                          NOT NULL,
    slug        TEXT,
    image       TEXT,
    description TEXT,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE product_images
(
    product_id BIGINT NOT NULL,
    image      TEXT
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       TEXT,
    slug        TEXT,
    price       DOUBLE PRECISION,
    description TEXT,
    quantity    INTEGER,
    rating      DOUBLE PRECISION,
    category_id BIGINT,
    status      TEXT,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE product_images
    ADD CONSTRAINT fk_product_images_on_product FOREIGN KEY (product_id) REFERENCES products (id);
INSERT INTO categories (name, slug, image, description)
VALUES
    ('Electronics', 'electronics', 'https://i.imgur.com/ZANVnHE.jpeg', NULL),
    ('REST-Update', 'rest-update', 'https://placeimg.com/640/480/any', NULL)
ON CONFLICT (name) DO NOTHING;

INSERT INTO categories (name, slug, image, description)
VALUES
    ('Electronics',  'electronics',  'https://i.imgur.com/ZANVnHE.jpeg', NULL),
    ('REST-Update',  'rest-update',  'https://placeimg.com/640/480/any', NULL)
ON CONFLICT (name) DO NOTHING;

-- 2) Products (no images here; they go to product_images)
--    Set quantity/rating NULL for now; status 'ACTIVE' (matches your enum).
INSERT INTO products (title, slug, price, description, quantity, rating, category_id, status) VALUES
                                                                                                  (
                                                                                                      'Sleek White & Orange Wireless Gaming Controller',
                                                                                                      'sleek-white-orange-wireless-gaming-controller',
                                                                                                      69,
                                                                                                      'Elevate your gaming experience with this state-of-the-art wireless controller, featuring a crisp white base with vibrant orange accents. Designed for precision play, the ergonomic shape and responsive buttons provide maximum comfort and control for endless hours of gameplay. Compatible with multiple gaming platforms, this controller is a must-have for any serious gamer looking to enhance their setup.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'Electronics'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Sleek Comfort-Fit Over-Ear Headphones',
                                                                                                      'sleek-comfort-fit-over-ear-headphones',
                                                                                                      28,
                                                                                                      'Experience superior sound quality with our Sleek Comfort-Fit Over-Ear Headphones, designed for prolonged use with cushioned ear cups and an adjustable, padded headband. Ideal for immersive listening, whether you''re at home, in the office, or on the move. Their durable construction and timeless design provide both aesthetically pleasing looks and long-lasting performance.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'Electronics'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Sleek Wireless Computer Mouse',
                                                                                                      'sleek-wireless-computer-mouse',
                                                                                                      10,
                                                                                                      'Experience smooth and precise navigation with this modern wireless mouse, featuring a glossy finish and a comfortable ergonomic design. Its responsive tracking and easy-to-use interface make it the perfect accessory for any desktop or laptop setup. The stylish blue hue adds a splash of color to your workspace, while its compact size ensures it fits neatly in your bag for on-the-go productivity.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'Electronics'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Sleek Modern Laptop for Professionals',
                                                                                                      'sleek-modern-laptop-for-professionals',
                                                                                                      97,
                                                                                                      'Experience cutting-edge technology and elegant design with our latest laptop model. Perfect for professionals on-the-go, this high-performance laptop boasts a powerful processor, ample storage, and a long-lasting battery life, all encased in a lightweight, slim frame for ultimate portability. Shop now to elevate your work and play.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'Electronics'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Sleek Modern Leather Sofa',
                                                                                                      'sleek-modern-leather-sofa',
                                                                                                      53,
                                                                                                      'Enhance the elegance of your living space with our Sleek Modern Leather Sofa. Designed with a minimalist aesthetic, it features clean lines and a luxurious leather finish. The robust metal legs provide stability and support, while the plush cushions ensure comfort. Perfect for contemporary homes or office waiting areas, this sofa is a statement piece that combines style with practicality.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'REST-Update'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Mid-Century Modern Wooden Dining Table',
                                                                                                      'mid-century-modern-wooden-dining-table',
                                                                                                      24,
                                                                                                      'Elevate your dining room with this sleek Mid-Century Modern dining table, featuring an elegant walnut finish and tapered legs for a timeless aesthetic. Its sturdy wood construction and minimalist design make it a versatile piece that fits with a variety of decor styles. Perfect for intimate dinners or as a stylish spot for your morning coffee.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'REST-Update'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Modern Elegance Teal Armchair',
                                                                                                      'modern-elegance-teal-armchair',
                                                                                                      25,
                                                                                                      'Elevate your living space with this beautifully crafted armchair, featuring a sleek wooden frame that complements its vibrant teal upholstery. Ideal for adding a pop of color and contemporary style to any room, this chair provides both superb comfort and sophisticated design. Perfect for reading, relaxing, or creating a cozy conversation nook.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'REST-Update'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Elegant Solid Wood Dining Table',
                                                                                                      'elegant-solid-wood-dining-table',
                                                                                                      67,
                                                                                                      'Enhance your dining space with this sleek, contemporary dining table, crafted from high-quality solid wood with a warm finish. Its sturdy construction and minimalist design make it a perfect addition for any home looking for a touch of elegance. Accommodates up to six guests comfortably and includes a striking fruit bowl centerpiece. The overhead lighting is not included.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'REST-Update'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Modern Minimalist Workstation Setup',
                                                                                                      'modern-minimalist-workstation-setup',
                                                                                                      49,
                                                                                                      'Elevate your home office with our Modern Minimalist Workstation Setup, featuring a sleek wooden desk topped with an elegant computer, stylish adjustable wooden desk lamp, and complimentary accessories for a clean, productive workspace. This setup is perfect for professionals seeking a contemporary look that combines functionality with design.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'REST-Update'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Stylish Red & Silver Over-Ear Headphones',
                                                                                                      'stylish-red-silver-over-ear-headphones',
                                                                                                      39,
                                                                                                      'Immerse yourself in superior sound quality with these sleek red and silver over-ear headphones. Designed for comfort and style, the headphones feature cushioned ear cups, an adjustable padded headband, and a detachable red cable for easy storage and portability. Perfect for music lovers and audiophiles who value both appearance and audio fidelity.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'Electronics'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Sleek Mirror Finish Phone Case',
                                                                                                      'sleek-mirror-finish-phone-case',
                                                                                                      27,
                                                                                                      'Enhance your smartphone''s look with this ultra-sleek mirror finish phone case. Designed to offer style with protection, the case features a reflective surface that adds a touch of elegance while keeping your device safe from scratches and impacts. Perfect for those who love a minimalist and modern aesthetic.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'Electronics'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Sleek Smartwatch with Vibrant Display',
                                                                                                      'sleek-smartwatch-with-vibrant-display',
                                                                                                      16,
                                                                                                      'Experience modern timekeeping with our high-tech smartwatch, featuring a vivid touch screen display, customizable watch faces, and a comfortable blue silicone strap. This smartwatch keeps you connected with notifications and fitness tracking while showcasing exceptional style and versatility.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'Electronics'),
                                                                                                      'ACTIVE'
                                                                                                  ),
                                                                                                  (
                                                                                                      'Elegant Golden-Base Stone Top Dining Table',
                                                                                                      'elegant-golden-base-stone-top-dining-table',
                                                                                                      66,
                                                                                                      'Elevate your dining space with this luxurious table, featuring a sturdy golden metal base with an intricate rod design that provides both stability and chic elegance. The smooth stone top in a sleek round shape offers a robust surface for your dining pleasure. Perfect for both everyday meals and special occasions, this table easily complements any modern or glam decor.',
                                                                                                      NULL, NULL,
                                                                                                      (SELECT id FROM categories WHERE name = 'REST-Update'),
                                                                                                      'ACTIVE'
                                                                                                  );

-- 3) Product images (each row links by product slug -> id)
INSERT INTO product_images (product_id, image) VALUES
                                                   ((SELECT id FROM products WHERE slug='sleek-white-orange-wireless-gaming-controller'), 'https://i.imgur.com/ZANVnHE.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-white-orange-wireless-gaming-controller'), 'https://i.imgur.com/Ro5z6Tn.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-white-orange-wireless-gaming-controller'), 'https://i.imgur.com/woA93Li.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='sleek-comfort-fit-over-ear-headphones'), 'https://i.imgur.com/SolkFEB.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-comfort-fit-over-ear-headphones'), 'https://i.imgur.com/KIGW49u.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-comfort-fit-over-ear-headphones'), 'https://i.imgur.com/mWwek7p.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='sleek-wireless-computer-mouse'), 'https://i.imgur.com/w3Y8NwQ.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-wireless-computer-mouse'), 'https://i.imgur.com/WJFOGIC.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-wireless-computer-mouse'), 'https://i.imgur.com/dV4Nklf.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='sleek-modern-laptop-for-professionals'), 'https://i.imgur.com/ItHcq7o.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-modern-laptop-for-professionals'), 'https://i.imgur.com/55GM3XZ.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-modern-laptop-for-professionals'), 'https://i.imgur.com/tcNJxoW.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='sleek-modern-leather-sofa'), 'https://i.imgur.com/Qphac99.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-modern-leather-sofa'), 'https://i.imgur.com/dJjpEgG.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-modern-leather-sofa'), 'https://i.imgur.com/MxJyADq.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='mid-century-modern-wooden-dining-table'), 'https://i.imgur.com/DMQHGA0.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='mid-century-modern-wooden-dining-table'), 'https://i.imgur.com/qrs9QBg.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='mid-century-modern-wooden-dining-table'), 'https://i.imgur.com/XVp8T1I.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='modern-elegance-teal-armchair'), 'https://i.imgur.com/6wkyyIN.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='modern-elegance-teal-armchair'), 'https://i.imgur.com/Ald3Rec.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='modern-elegance-teal-armchair'), 'https://i.imgur.com/dIqo03c.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='elegant-solid-wood-dining-table'), 'https://i.imgur.com/4lTaHfF.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='elegant-solid-wood-dining-table'), 'https://i.imgur.com/JktHE1C.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='elegant-solid-wood-dining-table'), 'https://i.imgur.com/cQeXQMi.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='modern-minimalist-workstation-setup'), 'https://i.imgur.com/3oXNBst.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='modern-minimalist-workstation-setup'), 'https://i.imgur.com/ErYYZnT.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='modern-minimalist-workstation-setup'), 'https://i.imgur.com/boBPwYW.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='stylish-red-silver-over-ear-headphones'), 'https://i.imgur.com/YaSqa06.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='stylish-red-silver-over-ear-headphones'), 'https://i.imgur.com/isQAliJ.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='stylish-red-silver-over-ear-headphones'), 'https://i.imgur.com/5B8UQfh.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='sleek-mirror-finish-phone-case'), 'https://i.imgur.com/yb9UQKL.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-mirror-finish-phone-case'), 'https://i.imgur.com/m2owtQG.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-mirror-finish-phone-case'), 'https://i.imgur.com/bNiORct.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='sleek-smartwatch-with-vibrant-display'), 'https://i.imgur.com/LGk9Jn2.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-smartwatch-with-vibrant-display'), 'https://i.imgur.com/1ttYWaI.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='sleek-smartwatch-with-vibrant-display'), 'https://i.imgur.com/sPRWnJH.jpeg'),

                                                   ((SELECT id FROM products WHERE slug='elegant-golden-base-stone-top-dining-table'), 'https://i.imgur.com/NWIJKUj.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='elegant-golden-base-stone-top-dining-table'), 'https://i.imgur.com/Jn1YSLk.jpeg'),
                                                   ((SELECT id FROM products WHERE slug='elegant-golden-base-stone-top-dining-table'), 'https://i.imgur.com/VNZRvx5.jpeg');
