CREATE TABLE order_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id    BIGINT                                  NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    total_price DECIMAL(19, 2),
    changed_at  TIMESTAMP,
    CONSTRAINT pk_order_history PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    total_price DECIMAL(19, 2),
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE order_history
    ADD CONSTRAINT FK_ORDER_HISTORY_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);